### ISSUE TITLE
can we publish this under the zapier npm org?

### ISSUE THREAD

**Issue by codekirei** [zapier/eslint-plugin-zapier#30]
I just tried to `npm publish` since we have a new version (`5.1.0`) and got an access denied error. I think this is because this package is currently published under @vitorbal's NPM account and not the org https://www.npmjs.com/org/zapier.

I _think_ all we need to do to get it in the org is change the  name to `@zapier/eslint-plugin-zapier`. We could also opt-in to the package staying public: https://www.npmjs.com/docs/orgs/publishing-an-org-scoped-package.html.

There maybe reasons we shouldn't move the package into the org, but I'm not sure — hopefully you have context there, @vitorbal :)

**Comment by vitorbal** [comment]
Done @codekirei, just published v5.1.1 under the zapier org!

There were really no reasons for publishing outside of it before, except that when I first started working on this I didn't know it existed 😛

The dependency graph only shows these repos as depending on `eslint-plugin-zapier`:
- babel-preset-zapier
- zapier-platform-app-converted-full-test
- zapier-platform-legacy-scripting-runner
- zapier-scripts

If you know any other repos, could you help me convert them to the new `@zapier/eslint-plugin-zapier` npm package?

**Comment by vitorbal** [comment]
Closing this as the package is now published under the zapier npm org.
